# Generated by Django 5.2.13 on 2026-09-02 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('role', models.CharField(blank=True, default='lecteur', max_length=50, verbose_name='Rôle utilisateur')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet de la demande')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité par le support')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message Support',
                'verbose_name_plural': 'Messages Support',
                'db_table': 'communications_contact_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
