# Generated by Django 5.2.13 on 2026-09-02 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(choices=[('public', 'Grand Public / Visiteurs'), ('student', 'Lecteurs & Étudiants'), ('wholesaler', 'Libraires & Grossistes'), ('university', 'Universités & Partenaires'), ('publisher', 'Éditeurs Tiers'), ('author', 'Auteurs'), ('manager', 'Gestionnaires Logistiques'), ('layout_artist', 'Maquettistes'), ('chief_layout', 'Chefs Maquettistes'), ('legal_reviewer', 'Relecteurs Juridiques'), ('admin', 'Administrateurs Plateforme')], default='student', max_length=50, verbose_name='Rôle ciblé')),
                ('category_label', models.CharField(max_length=150, verbose_name='Libellé catégorie')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du guide')),
                ('summary', models.TextField(verbose_name='Résumé / Objectif')),
                ('icon_name', models.CharField(default='BookOpen', max_length=50, verbose_name="Nom de l'icône Lucide")),
                ('steps', models.JSONField(default=list, verbose_name='Étapes pas-à-pas (JSON)')),
                ('faq', models.JSONField(blank=True, default=list, verbose_name='Questions fréquentes associées (JSON)')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_guides', to=settings.AUTH_USER_MODEL, verbose_name='Créé par (Admin)')),
            ],
            options={
                'verbose_name': "Guide d'Utilisation",
                'verbose_name_plural': "Guides d'Utilisation",
                'db_table': 'communications_guide_item',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
