# Generated by Django 5.2.13 on 2026-09-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_guideitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideitem',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name="URL de l'image d'illustration"),
        ),
        migrations.AddField(
            model_name='guideitem',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='URL de la vidéo explicative (YouTube / Cloudflare / MP4)'),
        ),
    ]
