# Generated by Django 5.2.13 on 2026-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_guideitem_image_url_guideitem_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideitem',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Corps riche (HTML / Markdown)'),
        ),
        migrations.AlterField(
            model_name='guideitem',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name="URL de l'image d'illustration (Cloudflare R2 / CDN)"),
        ),
        migrations.AlterField(
            model_name='guideitem',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='URL de la vidéo explicative (Cloudflare R2 MP4 / WebM ou externe)'),
        ),
    ]
