# Generated by Django 5.2.13 on 2026-09-02 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_guideitem_content_alter_guideitem_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('roles', models.JSONField(default=list, help_text='Liste des rôles cibles (ex: ["student", "wholesaler", "university", "publisher", "author", "manager", "layout_artist", "chief_layout", "legal_reviewer", "admin"])')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Guide',
                'verbose_name_plural': 'Catégories de Guide',
                'db_table': 'guide_categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Titre ou question de l'article", max_length=200)),
                ('content', models.TextField(help_text='Contenu HTML Tiptap ou Markdown')),
                ('video_url', models.URLField(blank=True, help_text='Lien vidéo externe (YouTube, Vimeo, MP4 direct...)', null=True)),
                ('stream_id', models.CharField(blank=True, max_length=100, verbose_name='ID Cloudflare Stream')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guides/images/%Y/%m/')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Image Cloudflare R2 / Cloudinary')),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='communications.guidecategory')),
            ],
            options={
                'verbose_name': 'Article de Guide',
                'verbose_name_plural': 'Articles de Guide',
                'db_table': 'guide_articles',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='GuideItem',
        ),
    ]
