# Generated by Django 5.2.13 on 2026-09-03 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_emailnotificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptPublicSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='N° de dossier')),
                ('first_name', models.CharField(max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name="Adresse e-mail de l'auteur")),
                ('phone', models.CharField(max_length=64, verbose_name='Téléphone / WhatsApp')),
                ('book_title', models.CharField(max_length=255, verbose_name='Titre du manuscrit')),
                ('genre', models.CharField(max_length=128, verbose_name='Genre littéraire / Discipline')),
                ('country', models.CharField(max_length=64, verbose_name='Pays')),
                ('summary', models.TextField(verbose_name="Résumé / Description de l'œuvre")),
                ('manuscript_file', models.FileField(blank=True, null=True, upload_to='manuscripts/%Y/%m/', verbose_name='Fichier manuscrit')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Taille en octets')),
                ('file_size_formatted', models.CharField(blank=True, default='', max_length=32, verbose_name='Taille formatée')),
                ('file_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='URL de téléchargement direct')),
                ('status', models.CharField(default='pending', max_length=32, verbose_name="Statut d'instruction")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
            ],
            options={
                'verbose_name': 'Soumission de Manuscrit',
                'verbose_name_plural': 'Soumissions de Manuscrits',
                'db_table': 'communications_manuscript_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_type', models.CharField(max_length=64, verbose_name='Type de partenariat')),
                ('organization_name', models.CharField(max_length=255, verbose_name="Nom de l'organisation")),
                ('contact_name', models.CharField(max_length=255, verbose_name='Nom & Fonction du contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('contact_phone', models.CharField(max_length=64, verbose_name='Téléphone / WhatsApp')),
                ('country', models.CharField(max_length=64, verbose_name='Pays')),
                ('message', models.TextField(blank=True, default='', verbose_name='Détails du besoin')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité par la direction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
            ],
            options={
                'verbose_name': 'Demande de Partenariat',
                'verbose_name_plural': 'Demandes de Partenariats',
                'db_table': 'communications_partnership_submission',
                'ordering': ['-created_at'],
            },
        ),
    ]
