# Generated by Django 5.2.7 on 2026-09-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_manuscriptpublicsubmission_partnershipsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptpublicsubmission',
            name='manuscript_file_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Référence R2 (téléversement direct)'),
        ),
    ]
