# Generated by Django 5.2.7 on 2026-09-05 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_manuscriptpublicsubmission_manuscript_file_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Adresse email professionnelle')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Téléphone / WhatsApp')),
                ('organization', models.CharField(blank=True, default='', max_length=255, verbose_name='Organisation / Établissement')),
                ('role_or_title', models.CharField(blank=True, default='', max_length=128, verbose_name='Fonction / Qualité')),
                ('category', models.CharField(choices=[('university', 'Université / Académie'), ('author', 'Auteur / Écrivain'), ('publisher', 'Éditeur Tiers / Partenaire'), ('institution', 'Ministère / Institution Publique'), ('partner', 'Diffuseur / Libraire / Partenaire B2B'), ('press', 'Presse & Média'), ('other', 'Autre contact')], default='other', max_length=32, verbose_name='Catégorie')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes internes & historique')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier contact')),
                ('emails_sent_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'emails envoyés")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_professional_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Contact Professionnel',
                'verbose_name_plural': 'Contacts Professionnels',
                'db_table': 'communications_professional_contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactEmailDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('body_snippet', models.TextField(verbose_name='Extrait du message')),
                ('status', models.CharField(default='sent', max_length=32, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_contact_emails', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur (Admin / Juriste)')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_emails', to='communications.professionalcontact', verbose_name='Contact destinataire')),
            ],
            options={
                'verbose_name': "Envoi d'Email Contact",
                'verbose_name_plural': "Envois d'Emails Contacts",
                'db_table': 'communications_contact_email_dispatch',
                'ordering': ['-sent_at'],
            },
        ),
    ]
