# Generated by Django 5.2.13 on 2026-08-20 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaffiliation',
            name='carte_etudiant_image',
            field=models.ImageField(blank=True, null=True, upload_to='justificatifs_scolarite/'),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='motif_rejet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_affiliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='EtudiantInscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, max_length=100)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('faculte', models.CharField(blank=True, default='', max_length=150)),
                ('filiere', models.CharField(blank=True, default='', max_length=150)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=20)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_matricules', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants_inscrits', to='partners.institution')),
            ],
            options={
                'unique_together': {('institution', 'matricule')},
            },
        ),
    ]
