# Generated by Django 5.2.13 on 2026-08-20 15:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_studentaffiliation_carte_etudiant_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentaffiliation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Nom du Doyen'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='disciplines',
            field=models.JSONField(blank=True, default=list, verbose_name='Disciplines enseignées'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='student_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'étudiants inscrits"),
        ),
        migrations.AddField(
            model_name='institution',
            name='academic_director_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Directeur des Affaires Académiques / Scolarité'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, default="Campus d'Abomey-Calavi, Bénin", verbose_name='Adresse géographique'),
        ),
        migrations.AddField(
            model_name='institution',
            name='bank_iban',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='RIB / IBAN / Compte Trésorerie'),
        ),
        migrations.AddField(
            model_name='institution',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Banque / Trésor Public'),
        ),
        migrations.AddField(
            model_name='institution',
            name='bank_swift',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Code BIC / SWIFT'),
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, default='Cotonou', max_length=128, verbose_name='Ville du campus'),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail Officiel de Contact'),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone Officiel'),
        ),
        migrations.AddField(
            model_name='institution',
            name='contract_reference',
            field=models.CharField(default='CTR-UNIV-2025-01', max_length=64, verbose_name='Réf. Convention Cadre'),
        ),
        migrations.AddField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='institution',
            name='momo_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Compte Mobile Money Institutionnel'),
        ),
        migrations.AddField(
            model_name='institution',
            name='rector_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Nom du Recteur / Président'),
        ),
        migrations.AddField(
            model_name='institution',
            name='royalty_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Taux de Redevance (%)'),
        ),
        migrations.AddField(
            model_name='institution',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Sigle court'),
        ),
        migrations.AddField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliations', to='partners.faculty'),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='level',
            field=models.CharField(default='Licence 1', max_length=32, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='student_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail personnel'),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Nom & Prénom'),
        ),
        migrations.AddField(
            model_name='studentaffiliation',
            name='student_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Code / Sigle (ex: FADESP, FSS, FASEG)'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom complet de la Faculté / UFR'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code / Sigle (ex: UAC, UCAD, UNA)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.CharField(default='BJ', max_length=10, verbose_name='Code Pays (BJ, SN, CI, NE, TG, GA, CD)'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='domain_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom de domaine web'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom complet de l'établissement"),
        ),
        migrations.AlterField(
            model_name='studentaffiliation',
            name='carte_etudiant_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL justificatif / carte'),
        ),
        migrations.AlterField(
            model_name='studentaffiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_affiliations', to='partners.institution'),
        ),
        migrations.AlterField(
            model_name='studentaffiliation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Validé / Actif'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu'), ('expired', 'Expiré')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentaffiliation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentaffiliation',
            name='student_card_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Matricule Académique'),
        ),
        migrations.CreateModel(
            name='UniversityBouquetSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du Bouquet')),
                ('bouquet_type', models.CharField(choices=[('discipline', 'Par Discipline'), ('faculty', 'Par Faculté'), ('university', 'Intégral Université'), ('custom', 'Personnalisé')], default='discipline', max_length=32)),
                ('faculty_code', models.CharField(blank=True, default='', max_length=32, verbose_name='Faculté associée')),
                ('discipline', models.CharField(blank=True, default='', max_length=128, verbose_name='Discipline')),
                ('books_count', models.PositiveIntegerField(default=0)),
                ('annual_price', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente'), ('expired', 'Expiré')], default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_subscriptions', to='partners.institution')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UniversityPaperOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('delivery_campus', models.CharField(max_length=255, verbose_name='Campus & Bâtiment de Faculté pour Livraison')),
                ('contact_person', models.CharField(blank=True, default='', max_length=128, verbose_name='Réceptionnaire')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone Réceptionnaire')),
                ('items', models.JSONField(default=list, verbose_name='Lignes de commande [{book_id, title, quantity, unit_price}]')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En préparation'), ('in_transit', 'En cours de livraison'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=32)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_orders', to='partners.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityRoyaltyStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('period', models.CharField(max_length=64, verbose_name='Période')),
                ('total_sales_catalog', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('royalty_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('net_royalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Réglé / Transféré'), ('pending', 'En traitement'), ('available', 'Disponible pour virement')], default='available', max_length=20)),
                ('pdf_statement_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_statements', to='partners.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
