# Generated by Django 5.2.7 on 2026-08-26 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_faculty_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('bouquet_type', models.CharField(choices=[('discipline', 'Par Discipline'), ('faculty', 'Par Faculté'), ('university', 'Intégral Université'), ('custom', 'Personnalisé')], default='discipline', max_length=32)),
                ('faculty_code', models.CharField(blank=True, default='', max_length=32)),
                ('discipline', models.CharField(blank=True, default='', max_length=128)),
                ('books_count', models.PositiveIntegerField(default=0)),
                ('annual_price', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='universitybouquetsubscription',
            name='offering_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
