# Generated by Django 5.2.7 on 2026-08-26 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_discipline_created_at_discipline_description_and_more'),
        ('partners', '0004_bouquetoffering_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquetoffering',
            name='books_count',
        ),
        migrations.AddField(
            model_name='bouquetoffering',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='bouquetoffering',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquet_offerings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bouquetoffering',
            name='custom_books',
            field=models.ManyToManyField(blank=True, related_name='custom_bouquet_offerings', to='catalog.ouvrage'),
        ),
        migrations.AddField(
            model_name='bouquetoffering',
            name='target_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquet_offerings_scoped', to='partners.institution'),
        ),
        migrations.AddField(
            model_name='bouquetoffering',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bouquetoffering',
            name='bouquet_type',
            field=models.CharField(choices=[('discipline', 'Par Discipline'), ('faculty', 'Par Faculté'), ('university', 'Intégral Université'), ('country', 'Par Pays'), ('custom', 'Personnalisé')], default='discipline', max_length=32),
        ),
        migrations.AlterField(
            model_name='universitybouquetsubscription',
            name='bouquet_type',
            field=models.CharField(choices=[('discipline', 'Par Discipline'), ('faculty', 'Par Faculté'), ('university', 'Intégral Université'), ('country', 'Par Pays'), ('custom', 'Personnalisé')], default='discipline', max_length=32),
        ),
    ]
