# Generated by Django 5.2.7 on 2026-09-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_clientbouquetsubscription_payment_transaction_and_more'),
        ('partners', '0005_remove_bouquetoffering_books_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitybouquetsubscription',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquet_subscriptions', to='commerce.paymenttransaction'),
        ),
    ]
