# Generated by Django 5.2.7 on 2026-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_universitybouquetsubscription_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='royalty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=15.0, max_digits=5, null=True, verbose_name='Taux de Redevance (%)'),
        ),
    ]
