# Generated by Antigravity on 2026-09-17

from django.db import migrations, models


def set_institution_types(apps, schema_editor):
    Institution = apps.get_model('partners', 'Institution')
    # Les 4 universités publiques partenaires historiques (ayants droit)
    partner_codes = ['UAC', 'UP', 'UNSTIM', 'UNA']
    Institution.objects.filter(code__in=partner_codes).update(institution_type='partner')
    # Toutes les autres institutions sont clientes (souscriptrices)
    Institution.objects.exclude(code__in=partner_codes).update(institution_type='client')


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_alter_institution_royalty_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(
                choices=[
                    ('partner', 'Université Partenaire (Ayant droit)'),
                    ('client', 'Université Cliente (Souscriptrice)'),
                ],
                db_index=True,
                default='client',
                max_length=20,
                verbose_name="Typologie de l'établissement",
            ),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['institution_type', 'is_active'], name='partners_in_institu_9a65d1_idx'),
        ),
        migrations.RunPython(set_institution_types, reverse_code=migrations.RunPython.noop),
    ]
