# Generated by Antigravity on 2026-09-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_institution_institution_type_and_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquetoffering',
            name='monthly_price',
            field=models.DecimalField(
                decimal_places=2,
                default=50000.0,
                max_digits=12,
                verbose_name='Tarif Mensuel (XOF)',
            ),
        ),
        migrations.AlterField(
            model_name='bouquetoffering',
            name='bouquet_type',
            field=models.CharField(
                choices=[
                    ('general', 'Bouquet Général (Catalogue Intégral)'),
                    ('discipline', 'Par Discipline'),
                    ('university', 'Intégral Université'),
                    ('country', 'Par Pays'),
                    ('custom', 'Personnalisé'),
                ],
                default='discipline',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='bouquetoffering',
            name='target_institution',
            field=models.ForeignKey(
                blank=True,
                help_text='Obligatoire pour le type Intégral Université',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bouquet_offerings_scoped',
                to='partners.institution',
            ),
        ),
        migrations.AddField(
            model_name='universitybouquetsubscription',
            name='subscription_period',
            field=models.CharField(
                choices=[('monthly', 'Mensuel (30j)'), ('annual', 'Annuel (365j)')],
                default='annual',
                max_length=10,
                verbose_name='Formule de souscription',
            ),
        ),
        migrations.AddField(
            model_name='universitybouquetsubscription',
            name='price_paid',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name='Montant acquitté (XOF)',
            ),
        ),
        migrations.AlterField(
            model_name='universitybouquetsubscription',
            name='bouquet_type',
            field=models.CharField(
                choices=[
                    ('general', 'Bouquet Général (Catalogue Intégral)'),
                    ('discipline', 'Par Discipline'),
                    ('university', 'Intégral Université'),
                    ('country', 'Par Pays'),
                    ('custom', 'Personnalisé'),
                ],
                default='discipline',
                max_length=32,
            ),
        ),
    ]
