# Generated by Django 5.2.13 on 2026-09-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_bouquetoffering_biperiod_pricing'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='institution',
            new_name='partners_in_institu_62bbd7_idx',
            old_name='partners_in_institu_9a65d1_idx',
        ),
        migrations.AlterField(
            model_name='bouquetoffering',
            name='annual_price',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=12, verbose_name='Tarif Annuel (XOF)'),
        ),
        migrations.AlterField(
            model_name='universitybouquetsubscription',
            name='faculty_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Faculté associée (obsolète)'),
        ),
    ]
