# Generated by Django 5.2.7 on 2026-08-09 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='auteur_principal', max_length=50)),
                ('pool_share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bookauthor')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_rights', to='catalog.ouvrage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RightTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_countries', models.JSONField(default=list)),
                ('exclusive', models.BooleanField(default=True)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ouvrage')),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_month', models.DateField()),
                ('total_reads_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('publisher_payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_settled', models.BooleanField(default=False)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ouvrage')),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyPayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_settled', models.BooleanField(default=False)),
                ('author_right', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rights.authorright')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_lines', to='rights.royaltycalculation')),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publisher_share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platform_share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ouvrage')),
            ],
        ),
    ]
