# Generated by Django 5.2.13 on 2026-08-20 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ouvrage_cover_image'),
        ('rights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contrat', models.CharField(db_index=True, max_length=64, unique=True)),
                ('type_contrat', models.CharField(choices=[('edition_auteur', "Contrat d'édition auteur"), ('partenariat_universite', 'Convention université partenaire'), ('editeur_tiers', 'Contrat éditeur tiers'), ('pre_edition', 'Accord de pré-édition'), ('avenant', 'Avenant contractuel')], db_index=True, default='edition_auteur', max_length=32)),
                ('titre', models.CharField(db_index=True, max_length=255)),
                ('contracting_party', models.CharField(db_index=True, default='', max_length=255)),
                ('parties_prenantes', models.JSONField(default=list)),
                ('fichier_contrat_path', models.CharField(default='', max_length=512)),
                ('file_name', models.CharField(default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('texte_integral_index', models.TextField(blank=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('pending_signature', 'En attente de signature'), ('expired', 'Expiré'), ('terminated', 'Résilié')], db_index=True, default='active', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRoyaltySuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiaire_nom', models.CharField(max_length=255)),
                ('pourcentage_suggere', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clause_extraite', models.TextField()),
                ('confiance_score', models.DecimalField(decimal_places=2, default=0.95, max_digits=3)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ouvrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ouvrage')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_ia', to='rights.contratlegal')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('momo', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('orange', 'Orange Money / Wave'), ('bank', 'Virement Bancaire (RIB/IBAN)')], default='momo', max_length=20)),
                ('account_details', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('processed', 'Traité / Viré')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreEditionDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_dossier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('titre_previsionnel', models.CharField(db_index=True, max_length=255)),
                ('auteur_nom', models.CharField(max_length=255)),
                ('universite_nom', models.CharField(blank=True, max_length=128)),
                ('faculte_nom', models.CharField(blank=True, max_length=128)),
                ('date_prevue_remise', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('en_attente_depot', 'En attente du manuscrit'), ('maquette_en_cours', 'Maquette en cours'), ('valide_legalement', 'Validé légalement'), ('archive', 'Archivé')], db_index=True, default='en_attente_depot', max_length=32)),
                ('notes_juridiques', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_pre_edition', to='rights.contratlegal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelanceEmailJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_relance', models.CharField(choices=[('rapport_droits_auteur', "Rapport périodique des droits d'auteur"), ('facture_impayee_client', 'Relance facture impayée client'), ('depot_en_attente', 'Relance dépôt en attente'), ('expiration_abonnement', 'Relance expiration abonnement')], db_index=True, max_length=32)),
                ('destinataire_email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('corps_message', models.TextField()),
                ('niveau_relance', models.IntegerField(default=1)),
                ('montant_du', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut_envoi', models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], default='envoye', max_length=16)),
                ('date_envoi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='RepartitionDroits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_libelle', models.CharField(default='Auteur Principal', max_length=100)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taux_papier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taux_numerique', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taux_audio_tts', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_effet', models.DateField(auto_now_add=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='droits_acquis', to=settings.AUTH_USER_MODEL)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions_droits', to='catalog.ouvrage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ouvrage', 'beneficiaire'), name='unique_repartition_ouvrage_beneficiaire')],
            },
        ),
    ]
