# Generated by Django 5.2.7 on 2026-08-24 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_contratlegal_airoyaltysuggestion_payoutrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preeditiondossier',
            name='auteur_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='preeditiondossier',
            name='auteur_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_editions_liees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorManuscriptSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('manuscript_file', models.FileField(blank=True, null=True, upload_to='manuscripts/')),
                ('version_type', models.CharField(choices=[('brouillon', 'Brouillon'), ('finale', 'Version finale')], default='brouillon', max_length=20)),
                ('suggested_summary', models.TextField(blank=True, default='')),
                ('suggested_language', models.CharField(default='Français', max_length=50)),
                ('status', models.CharField(choices=[('study_pending', "À l'étude"), ('catalog_preparation', 'En préparation catalogue'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='study_pending', max_length=30)),
                ('editorial_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
