# Generated by Django 5.2.7 on 2026-08-25 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0003_preeditiondossier_auteur_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtReminderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_remind_enabled', models.BooleanField(default=True)),
                ('first_reminder_days', models.IntegerField(default=7)),
                ('min_amount_threshold', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('max_reminders_count', models.IntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
