# Generated by Django 5.2.13 on 2026-08-25 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_discipline_created_at_discipline_description_and_more'),
        ('partners', '0003_alter_faculty_options_alter_institution_options_and_more'),
        ('publishers_portal', '0002_remove_validationworkflowstep_submission_and_more'),
        ('rights', '0004_debtreminderconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlegal',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_partenariat', to='partners.institution'),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='ouvrage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='catalog.ouvrage'),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='pre_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_associes', to='rights.preeditiondossier'),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_distribution', to='publishers_portal.publisher'),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='signataire_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_signes', to=settings.AUTH_USER_MODEL),
        ),
    ]
