# Generated by Django 5.2.7 on 2026-09-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0005_contratlegal_institution_contratlegal_ouvrage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtreminderconfig',
            name='reminder_frequency_days',
            field=models.IntegerField(default=5, help_text='Nombre de jours entre deux relances successives pour un même impayé'),
        ),
    ]
