# Generated by Django 5.2.7 on 2026-09-03 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0006_debtreminderconfig_reminder_frequency_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicManuscriptLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('book_title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('manuscript_file', models.FileField(upload_to='public_manuscript_leads/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contactée'), ('converted', 'Compte auteur créé'), ('rejected', 'Non retenue')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rights_public_manuscript_lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
