# Generated by Django 5.2.7 on 2026-09-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0007_publicmanuscriptlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmanuscriptlead',
            name='manuscript_file_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='publicmanuscriptlead',
            name='manuscript_file',
            field=models.FileField(blank=True, null=True, upload_to='public_manuscript_leads/%Y/%m/'),
        ),
    ]
