# Generated by Django 5.2.7 on 2026-09-05 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0008_publicmanuscriptlead_manuscript_file_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlegal',
            name='contracting_party_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='contracting_party_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='juriste_responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['legal_reviewer', 'admin', 'super_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_geres', to=settings.AUTH_USER_MODEL),
        ),
    ]
