# Generated by Django 5.2.7 on 2026-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0009_contratlegal_contracting_party_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltyrate',
            name='university_share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Taux de redevance université spécifique à ce livre/contrat — si vide, repli sur le taux général de l'institution.", max_digits=5, null=True),
        ),
    ]
