# Generated by Django 5.2.13 on 2026-09-06 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_ouvrage_has_audio_version_ouvrage_price_audio'),
        ('partners', '0005_remove_bouquetoffering_books_count_and_more'),
        ('publishers_portal', '0004_publisherbookdeposit_editorial_status_and_more'),
        ('rights', '0010_royaltyrate_university_share_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlegal',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='indexing_status',
            field=models.CharField(choices=[('pending', "En attente d'indexation"), ('processing', 'Analyse OCR en cours'), ('indexed', 'Indexé avec succès'), ('failed', "Échec d'indexation optique")], db_index=True, default='indexed', max_length=24),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='ocr_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='contratlegal',
            name='ocr_engine_used',
            field=models.CharField(blank=True, default='pymupdf_native', max_length=32),
        ),
        migrations.AddIndex(
            model_name='contratlegal',
            index=models.Index(fields=['indexing_status'], name='idx_contrat_idx_status'),
        ),
    ]
