# Generated by Django 5.2.7 on 2026-09-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0011_contratlegal_indexed_at_contratlegal_indexing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltycalculation',
            name='platform_revenue_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
