# Generated by Django 5.2.13 on 2026-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0012_royaltycalculation_platform_revenue_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='beneficiary_type',
            field=models.CharField(default='author', max_length=20),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='gross_base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='purpose_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='payout_receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
