# Generated by Django 5.2.13 on 2026-09-17 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0013_payoutrequest_beneficiary_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourrierOfficiel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(choices=[('royalty_author', 'Redevance Auteur'), ('royalty_university', 'Redevance Université'), ('royalty_publisher', 'Redevance Éditeur Tiers'), ('debt_reminder', 'Relance Impayé'), ('other', 'Correspondance Officielle')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('canceled', 'Annulé'), ('sent', 'Envoyé')], db_index=True, default='draft', max_length=20)),
                ('recipient_type', models.CharField(choices=[('author', 'Auteur'), ('university', 'Université Partenaire'), ('publisher', 'Éditeur Tiers'), ('client', 'Client Débiteur')], max_length=30)),
                ('recipient_id', models.CharField(blank=True, default='', max_length=100)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('period', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='FCFA', max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='courriers_officiels/%Y/%m/')),
                ('pdf_key', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_officiels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Courrier Officiel',
                'verbose_name_plural': 'Courriers Officiels',
                'db_table': 'rights_courrier_officiel',
                'ordering': ['-created_at'],
            },
        ),
    ]
