from django.urls import path
from .views import (
    AuthorDashboardKPIsView,
    AuthorBooksListView,
    AuthorBookDetailView,
    AuthorRoyaltiesStatementsView,
    AuthorPayoutRequestView,
    AdminPayoutDecisionView,
    AuthorSubmissionsView,
    AuthorOrderReturnView,
    ManuscriptReviewListView,
    ManuscriptReviewDecisionView,
    LegalKpisView,
    LegalContractsListView,
    LegalContractsFormOptionsView,
    LegalContractDetailView,
    LegalContractStreamView,
    LegalRoyaltiesListView,
    LegalRoyaltiesBatchView,
    LegalUniversityRoyaltiesListView,
    LegalPublisherRoyaltiesListView,
    LegalAiSuggestionsListView,
    LegalAiSuggestionDecisionView,
    LegalPreEditionsListView,
    LegalPreEditionDetailView,
    DebtReminderConfigView,
    LegalRelancesListView,
    LegalRedevancesStatementView,
    PublicManuscriptSubmitView,
    AdminManuscriptLeadsListView,
    AdminManuscriptLeadDecisionView,
    PublicManuscriptPresignedUrlView,
    LegalPendingPublicationListView,
    LegalPublishOuvrageView,
)

app_name = 'rights'

urlpatterns = [
    # Soumission Publique de Manuscrit & Suivi Admin
    path('public/manuscript-submit/', PublicManuscriptSubmitView.as_view(), name='public-manuscript-submit'),
    path('public/manuscript-presigned-url/', PublicManuscriptPresignedUrlView.as_view(), name='public-manuscript-presigned-url'),
    path('admin/manuscript-leads/', AdminManuscriptLeadsListView.as_view(), name='admin-manuscript-leads-list'),
    path('admin/manuscript-leads/<str:id>/', AdminManuscriptLeadDecisionView.as_view(), name='admin-manuscript-lead-decision'),

    # Auteur & Redevances
    path('author/kpis/', AuthorDashboardKPIsView.as_view(), name='author-kpis'),
    path('author/books/', AuthorBooksListView.as_view(), name='author-books'),
    path('author/books/<uuid:id>/', AuthorBookDetailView.as_view(), name='author-book-detail'),
    path('author/royalties/', AuthorRoyaltiesStatementsView.as_view(), name='author-royalties'),
    path('author/payout-request/', AuthorPayoutRequestView.as_view(), name='author-payout-request'),
    path('admin/payouts/<uuid:id>/decision/', AdminPayoutDecisionView.as_view(), name='admin-payout-decision'),
    path('author/submissions/', AuthorSubmissionsView.as_view(), name='author-submissions'),
    path('author/orders/<uuid:order_id>/return/', AuthorOrderReturnView.as_view(), name='author-order-return'),
    path('manuscripts/', ManuscriptReviewListView.as_view(), name='manuscripts-review-list'),
    path('manuscripts/<str:id>/decision/', ManuscriptReviewDecisionView.as_view(), name='manuscripts-review-decision'),

    # Juriste / Legal Reviewer
    path('legal/kpis/', LegalKpisView.as_view(), name='legal-kpis'),
    path('legal/contracts/form-options/', LegalContractsFormOptionsView.as_view(), name='legal-contracts-form-options'),
    path('legal/contracts/', LegalContractsListView.as_view(), name='legal-contracts-list'),
    path('legal/contracts/<uuid:id>/', LegalContractDetailView.as_view(), name='legal-contract-detail'),
    path('legal/contracts/<uuid:id>/stream/', LegalContractStreamView.as_view(), name='legal-contract-stream'),
    path('legal/royalties/', LegalRoyaltiesListView.as_view(), name='legal-royalties-list'),
    path('legal/royalties/batch/', LegalRoyaltiesBatchView.as_view(), name='legal-royalties-batch'),
    path('legal/royalties/universities/', LegalUniversityRoyaltiesListView.as_view(), name='legal-royalties-universities'),
    path('legal/royalties/publishers/', LegalPublisherRoyaltiesListView.as_view(), name='legal-royalties-publishers'),
    path('legal/royalties/publishers/<str:publisher_id>/', LegalPublisherRoyaltiesListView.as_view(), name='legal-royalties-publisher-detail'),
    path('legal/redevances/send-statement/', LegalRedevancesStatementView.as_view(), name='legal-redevances-statement'),
    path('legal/ai-suggestions/', LegalAiSuggestionsListView.as_view(), name='legal-ai-suggestions-list'),
    path('legal/ai-suggestions/<str:id>/decide/', LegalAiSuggestionDecisionView.as_view(), name='legal-ai-suggestion-decide'),
    path('legal/pre-editions/', LegalPreEditionsListView.as_view(), name='legal-pre-editions-list'),
    path('legal/pre-editions/<uuid:pk>/', LegalPreEditionDetailView.as_view(), name='legal-pre-edition-detail'),
    path('legal/relances/config/', DebtReminderConfigView.as_view(), name='legal-relances-config'),
    path('legal/relances/', LegalRelancesListView.as_view(), name='legal-relances-list'),
    path('legal/pending-publication/', LegalPendingPublicationListView.as_view(), name='legal-pending-publication-list'),
    path('legal/pending-publication/<str:id>/publish/', LegalPublishOuvrageView.as_view(), name='legal-publish-ouvrage'),
]

