# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('oauth2_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Nom de l'application cliente ou de l'institution", max_length=255)),
                ('allowed_return_origins', models.JSONField(default=list, help_text="Liste des domaines/origines autorises")),
                ('webhook_url', models.URLField(blank=True, help_text="URL de callback pour l'envoi des evenements temps reel", max_length=500)),
                ('webhook_secret', models.CharField(help_text="Cle secrete privee HMAC-SHA256", max_length=128)),
                ('quotas', models.JSONField(default=dict, help_text="Limites d'utilisation")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oauth_application', models.OneToOneField(blank=True, help_text="Application OAuth2", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to='oauth2_provider.application')),
            ],
            options={
                'verbose_name': 'Application Partenaire',
                'verbose_name_plural': 'Applications Partenaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerEndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_ref', models.CharField(db_index=True, help_text="Identifiant unique utilisateur", max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Nom complet', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Adresse email', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(help_text='Partenaire proprietaire', on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to='reader.partnerapp')),
            ],
            options={
                'verbose_name': 'Utilisateur Partenaire',
                'verbose_name_plural': 'Utilisateurs Partenaires',
            },
        ),
        migrations.CreateModel(
            name='ReaderSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('catalog_book', 'Catalogue Interne LAHATheque'), ('external_url', 'Document Externe Partenaire (BYOD)'), ('direct_upload', 'Upload Binaire Direct')], db_index=True, default='catalog_book', max_length=32)),
                ('custom_document_url', models.URLField(blank=True, max_length=1000)),
                ('custom_document_title', models.CharField(blank=True, max_length=255)),
                ('custom_document_author', models.CharField(blank=True, max_length=255)),
                ('custom_audio_url', models.URLField(blank=True, max_length=1000)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('theme', models.JSONField(default=dict)),
                ('quiz_config', models.JSONField(default=dict)),
                ('tts_config', models.JSONField(default=dict)),
                ('permissions', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('return_url', models.URLField(max_length=500)),
                ('last_page', models.IntegerField(default=0)),
                ('reading_time_seconds', models.IntegerField(default=0)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Creee'), ('opened', 'Ouverte'), ('in_progress', 'En cours'), ('finished', 'Terminee'), ('expired', 'Expiree'), ('revoked', 'Revoquee')], db_index=True, default='created', max_length=32)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reader.partnerenduser')),
                ('ouvrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader_sessions', to='catalog.ouvrage')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reader.partnerapp')),
            ],
            options={
                'verbose_name': 'Session de Lecture Hebergee',
                'verbose_name_plural': 'Sessions de Lecture Hebergees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultatQuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(default='Validation de Lecture', max_length=255)),
                ('score_percent', models.FloatField()),
                ('passing_score_percent', models.FloatField(default=70.0)),
                ('is_passed', models.BooleanField(default=False)),
                ('answers_detail', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_result', to='reader.readersession')),
            ],
            options={
                'verbose_name': 'Resultat de Quiz Session',
                'verbose_name_plural': 'Resultats de Quiz Sessions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('delivery_id', models.CharField(max_length=64, unique=True)),
                ('payload_json', models.TextField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('attempt_count', models.IntegerField(default=1)),
                ('is_success', models.BooleanField(db_index=True, default=False)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='reader.partnerapp')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='reader.readersession')),
            ],
            options={
                'verbose_name': 'Journal de Webhook',
                'verbose_name_plural': 'Journaux de Webhooks',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partnerenduser',
            index=models.Index(fields=['partner', 'external_ref'], name='reader_part_partner_f96e49_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerenduser',
            constraint=models.UniqueConstraint(fields=('partner', 'external_ref'), name='unique_partner_external_user'),
        ),
        migrations.AddIndex(
            model_name='readersession',
            index=models.Index(fields=['partner', 'status'], name='reader_read_partner_a6f6df_idx'),
        ),
        migrations.AddIndex(
            model_name='readersession',
            index=models.Index(fields=['token_hash', 'expires_at'], name='reader_read_token_h_444983_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['partner', 'event_type', '-delivered_at'], name='reader_webh_partner_3b1b68_idx'),
        ),
    ]
