# Generated by Django 5.2.13 on 2026-08-19 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ouvrage_price_digital_ouvrage_price_paper'),
        ('reader', '0001_initial'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readersession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Session de Lecture Hébergée', 'verbose_name_plural': 'Sessions de Lecture Hébergées'},
        ),
        migrations.AlterModelOptions(
            name='resultatquizsession',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Résultat de Quiz Session', 'verbose_name_plural': 'Résultats de Quiz Sessions'},
        ),
        migrations.RenameIndex(
            model_name='partnerenduser',
            new_name='reader_part_partner_cc0fd6_idx',
            old_name='reader_part_partner_f96e49_idx',
        ),
        migrations.RenameIndex(
            model_name='readersession',
            new_name='reader_read_partner_198ab9_idx',
            old_name='reader_read_partner_a6f6df_idx',
        ),
        migrations.RenameIndex(
            model_name='readersession',
            new_name='reader_read_token_h_09f376_idx',
            old_name='reader_read_token_h_444983_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooklog',
            new_name='reader_webh_partner_6c22b2_idx',
            old_name='reader_webh_partner_3b1b68_idx',
        ),
        migrations.AlterField(
            model_name='partnerapp',
            name='allowed_return_origins',
            field=models.JSONField(default=list, help_text='Liste des domaines/origines autorisés pour la redirection return_url (anti-open-redirect)'),
        ),
        migrations.AlterField(
            model_name='partnerapp',
            name='oauth_application',
            field=models.OneToOneField(blank=True, help_text="Application OAuth2 pour l'authentification Client Credentials", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerapp',
            name='quotas',
            field=models.JSONField(default=dict, help_text="Limites d'utilisation (max_concurrent_sessions, max_daily_requests, etc.)"),
        ),
        migrations.AlterField(
            model_name='partnerapp',
            name='webhook_secret',
            field=models.CharField(help_text='Clé secrète privée utilisée pour la signature HMAC-SHA256 des webhooks', max_length=128),
        ),
        migrations.AlterField(
            model_name='partnerapp',
            name='webhook_url',
            field=models.URLField(blank=True, help_text="URL de callback pour l'envoi des événements temps réel", max_length=500),
        ),
        migrations.AlterField(
            model_name='partnerenduser',
            name='display_name',
            field=models.CharField(blank=True, help_text="Nom complet de l'apprenant pour le filigrane nominatif", max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerenduser',
            name='email',
            field=models.EmailField(blank=True, help_text="Adresse email de l'apprenant pour le filigrane et traçage", max_length=254),
        ),
        migrations.AlterField(
            model_name='partnerenduser',
            name='external_ref',
            field=models.CharField(db_index=True, help_text="Identifiant unique de l'utilisateur dans le système d'origine du partenaire", max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerenduser',
            name='partner',
            field=models.ForeignKey(help_text='Partenaire propriétaire de cet utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to='reader.partnerapp'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='custom_audio_url',
            field=models.URLField(blank=True, help_text="URL distante optionnelle pour la piste audio d'accompagnement", max_length=1000),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='custom_document_author',
            field=models.CharField(blank=True, help_text='Auteur ou formateur du document externe', max_length=255),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='custom_document_title',
            field=models.CharField(blank=True, help_text='Titre du document externe affiché dans le lecteur', max_length=255),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='custom_document_url',
            field=models.URLField(blank=True, help_text='URL distante HTTPS du fichier PDF/Office si source_type=external_url', max_length=1000),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='end_user',
            field=models.ForeignKey(help_text='Utilisateur final consommant cette session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reader.partnerenduser'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='last_page',
            field=models.IntegerField(default=0, help_text='Dernière page consultée'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Métadonnées arbitraires transmises par le partenaire (course_id, module_id, etc.)'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='ouvrage',
            field=models.ForeignKey(blank=True, help_text='Ouvrage du catalogue si source_type=catalog_book', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader_sessions', to='catalog.ouvrage'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='partner',
            field=models.ForeignKey(help_text='Application partenaire ayant généré cette session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reader.partnerapp'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='permissions',
            field=models.JSONField(default=dict, help_text='Permissions accordées à la session (allow_tts, allow_annotations, allow_quiz)'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='quiz_config',
            field=models.JSONField(default=dict, help_text="Configuration des questions et règles d'évaluation du quiz"),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='reading_time_seconds',
            field=models.IntegerField(default=0, help_text='Temps de lecture cumulé en secondes'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='return_url',
            field=models.URLField(help_text="URL de redirection de l'utilisateur après fin de lecture", max_length=500),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='source_type',
            field=models.CharField(choices=[('catalog_book', 'Catalogue Interne LAHAThèque'), ('external_url', 'Document Externe Partenaire (BYOD)'), ('direct_upload', 'Upload Binaire Direct')], db_index=True, default='catalog_book', help_text='Provenance du document à lire', max_length=32),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='status',
            field=models.CharField(choices=[('created', 'Créée'), ('opened', 'Ouverte'), ('in_progress', 'En cours'), ('finished', 'Terminée'), ('expired', 'Expirée'), ('revoked', 'Révoquée')], db_index=True, default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='theme',
            field=models.JSONField(default=dict, help_text='Configuration de la charte graphique partenaire (couleurs, logo, marque)'),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='token_hash',
            field=models.CharField(db_index=True, help_text='Empreinte SHA-256 du token de session JWT éphémère', max_length=64),
        ),
        migrations.AlterField(
            model_name='readersession',
            name='tts_config',
            field=models.JSONField(default=dict, help_text='Configuration de la synthèse vocale (voix, débit, langues)'),
        ),
        migrations.AlterField(
            model_name='resultatquizsession',
            name='answers_detail',
            field=models.JSONField(default=list, help_text='Détail des réponses soumises pour chaque question'),
        ),
        migrations.AlterField(
            model_name='resultatquizsession',
            name='is_passed',
            field=models.BooleanField(default=False, help_text='Indique si le seuil a été atteint'),
        ),
        migrations.AlterField(
            model_name='resultatquizsession',
            name='passing_score_percent',
            field=models.FloatField(default=70.0, help_text='Seuil de réussite exigé'),
        ),
        migrations.AlterField(
            model_name='resultatquizsession',
            name='score_percent',
            field=models.FloatField(help_text='Score obtenu en pourcentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='resultatquizsession',
            name='session',
            field=models.OneToOneField(help_text='Session de lecture associée à ce quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_result', to='reader.readersession'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='attempt_count',
            field=models.IntegerField(default=1, help_text="Nombre de tentatives d'émission effectuées"),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='delivery_id',
            field=models.CharField(help_text="UUID unique de l'envoi pour l'idempotence", max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='event_type',
            field=models.CharField(db_index=True, help_text="Type d'événement (reader.session.opened, reader.quiz.completed, etc.)", max_length=64),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='is_success',
            field=models.BooleanField(db_index=True, default=False, help_text='Vrai si le code HTTP est 2xx'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='payload_json',
            field=models.TextField(help_text='Contenu brut du payload JSON transmis'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='response_body',
            field=models.TextField(blank=True, help_text='Corps de réponse renvoyé par le serveur tiers'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='status_code',
            field=models.IntegerField(blank=True, help_text='Code HTTP renvoyé par le serveur partenaire', null=True),
        ),
    ]
