# Generated by Django 5.2.7 on 2026-08-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_readersession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapp',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant public complet du client OAuth2 Machine-to-Machine', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partnerapp',
            name='client_secret_hash',
            field=models.CharField(blank=True, help_text="Empreinte SHA-256 du secret client. Le secret en clair n'est JAMAIS stocké.", max_length=128),
        ),
        migrations.AddField(
            model_name='partnerapp',
            name='client_secret_last4',
            field=models.CharField(blank=True, help_text='4 derniers caractères du secret pour affichage masqué (ex: ****a4f2)', max_length=4),
        ),
    ]
