# Generated by Django 5.2.7 on 2026-08-22 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_add_partner_client_id_and_secret_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='reader.partnerapp')),
            ],
            options={
                'verbose_name': 'Journal de Requête API (Réel)',
                'verbose_name_plural': 'Journaux de Requêtes API (Réels)',
                'ordering': ['-created_at'],
            },
        ),
    ]
