# Generated by Django 5.2.7 on 2026-09-01 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_remove_bouquetoffering_books_count_and_more'),
        ('reader', '0004_add_api_request_log_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapp',
            name='linked_institution',
            field=models.ForeignKey(blank=True, help_text='Établissement/Institution académique rattaché à cette application partenaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_apps', to='partners.institution'),
        ),
    ]
