# Generated by Django 5.2.7 on 2026-09-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_remove_bouquetoffering_books_count_and_more'),
        ('reader', '0005_partnerapp_linked_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapp',
            name='restricted_bouquet',
            field=models.ForeignKey(blank=True, help_text="Si défini, cette clé API n'a accès qu'aux livres de ce bouquet précis.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_apps_restricted', to='partners.bouquetoffering'),
        ),
    ]
