# Generated by Antigravity on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_bouquetoffering_biperiod_pricing'),
        ('reader', '0006_partnerapp_restricted_bouquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapp',
            name='access_mode',
            field=models.CharField(
                choices=[('catalog_only', 'Catalogue Seul'), ('full_reader', 'Lecteur Intégré')],
                default='catalog_only',
                help_text="Mode d'accès accordé à la clé API",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='partnerapp',
            name='restricted_bouquets',
            field=models.ManyToManyField(
                blank=True,
                help_text="Périmètre cumulé de tous les bouquets souscrits par l'institution partenaire.",
                related_name='partner_apps_multi',
                to='partners.bouquetoffering',
            ),
        ),
    ]
