# Generated by Django 5.2.13 on 2026-09-18 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_rename_partners_in_institu_9a65d1_idx_partners_in_institu_62bbd7_idx_and_more'),
        ('reader', '0007_partnerapp_restricted_bouquets_and_access_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapp',
            name='restricted_bouquet',
            field=models.ForeignKey(blank=True, help_text="Si défini, cette clé API n'a accès qu'aux livres de ce bouquet précis (rétro-compatibilité).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_apps_restricted', to='partners.bouquetoffering'),
        ),
    ]
