# Generated by Django 5.2.7 on 2026-08-09 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rccm_number', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('contact_email', models.EmailField(max_length=254)),
                ('bank_iban', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('raw_file', models.FileField(upload_to='submissions/')),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers_portal.publisher')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='publishers_portal.submissiondraft')),
            ],
        ),
    ]
