# Generated by Django 5.2.13 on 2026-08-20 15:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationworkflowstep',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='validationworkflowstep',
            name='assigned_to',
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Profil Éditeur Tiers', 'verbose_name_plural': 'Profils Éditeurs Tiers'},
        ),
        migrations.AddField(
            model_name='publisher',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Banque de Domiciliation'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='bank_swift',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Code BIC / SWIFT'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='city',
            field=models.CharField(default='Cotonou', max_length=128, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Raison Sociale ou Nom d'Auteur/Éditeur"),
        ),
        migrations.AddField(
            model_name='publisher',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Responsable / Nom du Contact'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone Direct / Astreinte'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='contract_reference',
            field=models.CharField(default='CTR-PUB-2025-01', max_length=64, verbose_name='Réf. Contrat de Mandat'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='contractual_royalty_rate',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=5, verbose_name='Taux Contractuel de Redevance (%)'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publisher',
            name='entity_type',
            field=models.CharField(choices=[('company', "Maison d'Édition / Personne Morale"), ('individual', 'Éditeur Indépendant / Auto-Éditeur (Personne Physique)')], default='company', max_length=20, verbose_name="Type d'Entité"),
        ),
        migrations.AddField(
            model_name='publisher',
            name='headquarters_address',
            field=models.TextField(blank=True, default='Cotonou, Bénin', verbose_name='Adresse Postale / Siège'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='identity_card_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Numéro CNI / Passeport (si particulier)'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Partenaire Certifié & Validé'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='momo_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Compte Mobile Money (MTN/Moov/Orange/Wave)'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='nif_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Numéro NIF / IFU'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='trade_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom Commercial / Enseigne'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='bank_iban',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Numéro IBAN / Compte Bancaire'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail de Facturation & Notifications'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='BJ', max_length=10, verbose_name='Pays du Siège / Résidence'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom Principal'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='rccm_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Numéro RCCM (si société)'),
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publishers_profile',
        ),
        migrations.CreateModel(
            name='PublisherApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Libellé du connecteur ERP')),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(max_length=255)),
                ('client_secret_masked', models.CharField(max_length=64)),
                ('permissions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Révoquée')], default='active', max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='publishers_portal.publisher')),
            ],
            options={
                'db_table': 'publishers_api_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublisherAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_id', models.CharField(max_length=64)),
                ('book_title', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=64)),
                ('user_masked', models.CharField(max_length=64)),
                ('device_type', models.CharField(max_length=64)),
                ('ip_address_masked', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='publishers_portal.publisher')),
            ],
            options={
                'db_table': 'publishers_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PublisherBatchImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('onix_3', 'ONIX 3.0 XML'), ('csv', 'CSV Tableur'), ('zip', 'Archive ZIP')], max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('processing', 'En cours'), ('completed', 'Terminé avec succès'), ('completed_with_errors', 'Terminé avec erreurs'), ('failed', 'Échec critique')], default='processing', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_imports', to='publishers_portal.publisher')),
            ],
            options={
                'db_table': 'publishers_batch_import_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublisherBookDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre Principal')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Sous-Titre')),
                ('isbn_digital', models.CharField(db_index=True, max_length=64, verbose_name='ISBN Numérique (EPUB/PDF)')),
                ('isbn_print', models.CharField(blank=True, default='', max_length=64, verbose_name='ISBN Papier')),
                ('doi', models.CharField(blank=True, default='', max_length=128, verbose_name='Identifiant DOI')),
                ('authors', models.JSONField(default=list, verbose_name='Auteurs Principaux')),
                ('contributors', models.JSONField(blank=True, default=list, verbose_name='Contributeurs (Traducteurs, Préfaciers)')),
                ('discipline', models.CharField(db_index=True, max_length=128, verbose_name='Discipline Académique')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name="Langue de l'ouvrage")),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Mots-Clés Thématiques')),
                ('target_audience', models.CharField(default='universitaire', max_length=64, verbose_name='Public Cible')),
                ('price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Prix Public Unitaire')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('sales_model', models.CharField(default='purchase', max_length=32, verbose_name='Modèle Commercial')),
                ('allowed_territories', models.JSONField(default=list, verbose_name="Territoires d'Exploitation")),
                ('embargo_date', models.DateField(blank=True, null=True, verbose_name="Date Fin d'Embargo")),
                ('summary', models.TextField(default="Résumé de l'ouvrage.", verbose_name='Résumé / 4e de couverture')),
                ('authors_bio', models.TextField(blank=True, default='', verbose_name='Biographie Auteurs')),
                ('cover_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL Couverture')),
                ('file_url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL Fichier')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('audio', 'Audio')], default='pdf', max_length=10)),
                ('licence_type', models.CharField(default='tous_droits_reserves', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En cours de validation'), ('revision_requested', 'Corrections demandées'), ('approved', 'Validé par le comité'), ('published', 'Publié sur la vitrine')], db_index=True, default='pending', max_length=32)),
                ('validation_step', models.CharField(choices=[('step_1_deposited', '1. Dépôt initial effectué'), ('step_2_auto_check', '2. Contrôle automatique technique'), ('step_3_editorial_review', '3. Examen éditorial LAHA'), ('step_4_notification', '4. Notification & Validation'), ('step_5_published', '5. Publication finale vitrine')], default='step_1_deposited', max_length=64)),
                ('editorial_comment', models.TextField(blank=True, default='', verbose_name='Commentaires du Comité LAHA')),
                ('consultations_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('watermark_enabled', models.BooleanField(default=True)),
                ('watermark_position', models.CharField(default='bottom-right', max_length=32)),
                ('watermark_opacity', models.PositiveIntegerField(default=30)),
                ('lcp_drm_enabled', models.BooleanField(default=True)),
                ('disable_copy_paste', models.BooleanField(default=True)),
                ('disable_print', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='publishers_portal.publisher')),
            ],
            options={
                'db_table': 'publishers_book_deposit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublisherRoyaltyPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('period', models.CharField(max_length=64, verbose_name='Période (ex: Octobre 2025)')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('royalty_rate', models.DecimalField(decimal_places=2, default=22.0, max_digits=5)),
                ('net_royalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Réglé'), ('pending', 'En traitement'), ('failed', 'Échoué')], default='paid', max_length=20)),
                ('pdf_statement_url', models.CharField(blank=True, default='', max_length=500)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_payments', to='publishers_portal.publisher')),
            ],
            options={
                'db_table': 'publishers_royalty_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SubmissionDraft',
        ),
        migrations.DeleteModel(
            name='ValidationWorkflowStep',
        ),
    ]
