# Generated by Django 5.2.7 on 2026-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers_portal', '0002_remove_validationworkflowstep_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherroyaltypayment',
            name='pdf_statement_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
