# Generated by Django 5.2.7 on 2026-08-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers_portal', '0003_alter_publisherroyaltypayment_pdf_statement_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherbookdeposit',
            name='editorial_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('revision_requested', 'Corrections demandées')], default='pending', max_length=20, verbose_name='Conformité éditoriale (Chef Maquettiste)'),
        ),
        migrations.AddField(
            model_name='publisherbookdeposit',
            name='rights_comment',
            field=models.TextField(blank=True, default='', verbose_name='Commentaires du Juriste'),
        ),
        migrations.AddField(
            model_name='publisherbookdeposit',
            name='rights_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('revision_requested', 'Corrections demandées')], default='pending', max_length=20, verbose_name='Vérification des droits (Juriste)'),
        ),
    ]
