# Generated by Django 5.2.13 on 2026-08-20 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ouvrage_cover_image'),
        ('commerce', '0002_order_lignecommande_physicaldelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('pays', models.CharField(db_index=True, max_length=64)),
                ('ville', models.CharField(max_length=128)),
                ('adresse', models.TextField()),
                ('responsable_nom', models.CharField(blank=True, default='', max_length=128)),
                ('telephone', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commerce_entrepot',
                'ordering': ['pays', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='StockOuvrage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_reelle', models.IntegerField(default=0)),
                ('quantite_reservee', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('last_restock_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_ouvrages', to='commerce.entrepot')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_entrepots', to='catalog.ouvrage')),
            ],
            options={
                'db_table': 'commerce_stock_ouvrage',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('restock', 'Réassort fournisseur'), ('sale', 'Sortie vente commande'), ('return', 'Retour client / Annulation'), ('adjustment', 'Ajustement inventaire / Avarie'), ('manual_exit', 'Sortie manuelle')], db_index=True, max_length=32)),
                ('quantite', models.IntegerField()),
                ('reference_document', models.CharField(blank=True, default='', max_length=64)),
                ('motif', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_effectues', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='commerce.stockouvrage')),
            ],
            options={
                'db_table': 'commerce_mouvement_stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockouvrage',
            constraint=models.UniqueConstraint(fields=('ouvrage', 'entrepot'), name='unique_stock_ouvrage_par_entrepot'),
        ),
    ]
