# Generated by Django 5.2.13 on 2026-08-20 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ouvrage_cover_image'),
        ('commerce', '0003_entrepot_stockouvrage_mouvementstock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleDiscountTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Nom du Palier (ex: Grand Compte)')),
                ('min_quantity', models.PositiveIntegerField(default=20, verbose_name='Quantité Minimale Requise')),
                ('digital_discount_percent', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Remise Licences Numériques (%)')),
                ('print_discount_percent', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, verbose_name='Remise Exemplaires Papier (%)')),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Palier de Remise Grossiste',
                'verbose_name_plural': 'Paliers de Remises Grossistes',
                'db_table': 'commerce_wholesale_discount_tier',
            },
        ),
        migrations.CreateModel(
            name='WholesaleNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('nouveaute', 'Nouveauté éditoriale'), ('meilleure_vente', 'Meilleure vente'), ('reassort', 'Réassort de stock'), ('expedition', 'Expédition transporteur')], default='nouveaute', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_notifications', to='catalog.ouvrage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commerce_wholesale_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('contact_phone', models.CharField(max_length=32)),
                ('total_digital_licenses', models.PositiveIntegerField(default=0)),
                ('total_print_copies', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée (Proforma émise)'), ('processing', 'En préparation / Expédition'), ('delivered', 'Livrée & Licences activées'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=32)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=128)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=128)),
                ('invoice_url', models.CharField(blank=True, default='', max_length=500)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande Grossiste',
                'verbose_name_plural': 'Commandes Grossistes',
                'db_table': 'commerce_wholesale_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.JSONField(default=list)),
                ('isbn', models.CharField(blank=True, default='', max_length=64)),
                ('digital_licenses_qty', models.PositiveIntegerField(default=0)),
                ('digital_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('print_copies_qty', models.PositiveIntegerField(default=0)),
                ('print_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_order_items', to='catalog.ouvrage')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.wholesaleorder')),
            ],
            options={
                'verbose_name': 'Ligne Commande Grossiste',
                'verbose_name_plural': 'Lignes Commandes Grossistes',
                'db_table': 'commerce_wholesale_order_item',
            },
        ),
        migrations.CreateModel(
            name='WholesaleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='Raison Sociale')),
                ('trade_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom Commercial / Enseigne')),
                ('nif_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Numéro NIF / IFU')),
                ('rccm_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Numéro RCCM')),
                ('contact_person', models.CharField(max_length=128, verbose_name='Responsable Achats / Contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email Réception Factures')),
                ('contact_phone', models.CharField(max_length=32, verbose_name="Téléphone d'Astreinte")),
                ('country', models.CharField(default='BJ', max_length=10, verbose_name='Pays')),
                ('city', models.CharField(default='Cotonou', max_length=128, verbose_name='Ville')),
                ('headquarters_address', models.TextField(verbose_name='Adresse Siège Social')),
                ('warehouse_address', models.TextField(verbose_name='Adresse Entrepôt de Réception')),
                ('payment_terms', models.CharField(default='Virement bancaire / Mobile Money à validation de facture proforma', max_length=255)),
                ('verified_partner', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='commerce.wholesalediscounttier', verbose_name='Palier Tarifaire Assigné')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Grossiste',
                'verbose_name_plural': 'Profils Grossistes',
                'db_table': 'commerce_wholesale_profile',
            },
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commerce.wholesaleprofile'),
        ),
    ]
