# Generated by Django 5.2.7 on 2026-08-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_wholesalediscounttier_wholesalenotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('carte', 'Carte bancaire')], default='mobile_money', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='type_commande',
            field=models.CharField(choices=[('rentree_scolaire', 'Rentrée scolaire'), ('personnel', 'Personnel'), ('institutionnel', 'Institutionnel')], default='personnel', max_length=20),
        ),
        migrations.AddField(
            model_name='physicaldelivery',
            name='date_livraison_souhaitee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicaldelivery',
            name='plage_horaire_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicaldelivery',
            name='plage_horaire_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
