# Generated by Django 5.2.7 on 2026-08-26 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_order_credit_due_date_order_credit_granted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleorder',
            name='credit_due_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance de paiement du crédit"),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='credit_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_credits_accordes', to=settings.AUTH_USER_MODEL, verbose_name='Validateur du crédit'),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='is_credit_purchase',
            field=models.BooleanField(default=False, verbose_name='Achat / Dépôt à Crédit Grossiste'),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='return_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motif de retour des invendus'),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de retour d'invendus"),
        ),
    ]
