# Generated by Django 5.2.13 on 2026-09-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_country'),
        ('commerce', '0008_clientbouquetsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleorderitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_order_items', to='catalog.ouvrage'),
        ),
    ]
