# Generated by Django 5.2.7 on 2026-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_wholesaleorderitem_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaldelivery',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frais de livraison définis par le Gestionnaire selon le service choisi', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='physicaldelivery',
            name='delivery_service',
            field=models.CharField(blank=True, default='', help_text='Service de livraison choisi par le Gestionnaire (ex: DHL, coursier local, retrait en agence)', max_length=100),
        ),
    ]
