# Generated by Django 5.2.7 on 2026-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_physicaldelivery_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='format_type',
            field=models.CharField(choices=[('digital', 'Numérique (EPUB/PDF)'), ('paper', 'Livre Papier'), ('audio', 'Livre Audio (Streaming)')], default='digital', max_length=20),
        ),
    ]
