# Generated by Django 5.2.13 on 2026-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_lignecommande_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='selected_language',
            field=models.CharField(default='fr', max_length=10, verbose_name='Langue sélectionnée (exemplaires physiques)'),
        ),
    ]
