# Generated by Django 5.2.7 on 2026-09-10 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_ouvragelanguageversion'),
        ('commerce', '0012_lignecommande_selected_language'),
        ('partners', '0005_remove_bouquetoffering_books_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientbouquetsubscription',
            index=models.Index(fields=['user', 'status', 'start_date', 'end_date'], name='commerce_cl_user_id_08c1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['ouvrage', 'format_type'], name='commerce_li_ouvrage_52056c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['statut_paiement', 'is_credit_purchase'], name='commerce_or_statut__dfd524_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'is_active'], name='commerce_su_user_id_da6b77_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['institution', 'is_active'], name='commerce_su_institu_398388_idx'),
        ),
    ]
