# Generated by Django 5.2.13 on 2026-09-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_clientbouquetsubscription_commerce_cl_user_id_08c1e1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('success', 'Succès'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=30),
        ),
    ]
