# Generated by Django 5.2.7 on 2026-09-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_clientbouquetsubscription_commerce_cl_user_id_08c1e1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbouquetsubscription',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_bouquet_subscriptions', to='commerce.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='clientbouquetsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
