# Generated by Django 5.2.13 on 2026-09-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_alter_paymenttransaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='abandoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_payment_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_orders_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_payment_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('momo_direct', 'Mobile Money direct (Flotte)'), ('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('cheque', 'Chèque'), ('credit', 'Achat à crédit')], default='mobile_money', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='statut_paiement',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('credit', 'Achat à crédit'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('abandoned', 'Panier abandonné'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
    ]
