# Generated by Django 5.2.13 on 2026-09-11 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_order_abandoned_at_order_last_reminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail client comptoir'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom client comptoir'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone client comptoir'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_immediate_handover',
            field=models.BooleanField(default=False, verbose_name='Remise en main propre immédiate'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pos_order',
            field=models.BooleanField(default=False, verbose_name='Vente comptoir / boutique'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
