# Generated by Django on 2026-09-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_clientbouquetsubscription_payment_transaction_and_more'),
        ('commerce', '0016_order_guest_email_order_guest_name_order_guest_phone_and_more'),
    ]

    operations = [
    ]
