# Generated by Django 5.2.7 on 2026-09-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_merge_20260911_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_status',
            field=models.CharField(choices=[('not_applicable', 'Non applicable'), ('pending_approval', "En attente d'approbation"), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='not_applicable', max_length=30, verbose_name="Statut d'approbation du crédit"),
        ),
    ]
