# Generated by Antigravity on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_order_credit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbouquetsubscription',
            name='subscription_period',
            field=models.CharField(
                choices=[('monthly', 'Mensuel (30j)'), ('annual', 'Annuel (365j)')],
                default='monthly',
                max_length=10,
                verbose_name='Formule de souscription',
            ),
        ),
    ]
