# Generated by Django 5.2.7 on 2026-08-09 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_print', models.BooleanField(default=False)),
                ('allow_copy', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=False)),
                ('watermark_visible', models.BooleanField(default=True)),
                ('watermark_text_template', models.CharField(default='Licence accordée à {email}', max_length=255)),
                ('invisible_watermark_enabled', models.BooleanField(default=False)),
                ('ouvrage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protection_config', to='catalog.ouvrage')),
            ],
        ),
        migrations.CreateModel(
            name='TraceAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=2)),
                ('user_agent', models.TextField()),
                ('device_fingerprint', models.CharField(max_length=255)),
                ('access_type', models.CharField(max_length=50)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ouvrage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
