# Generated by Django 5.2.7 on 2026-08-10 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('protection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('highlight', 'Surlignage'), ('note', 'Note')], default='highlight', max_length=20)),
                ('position_data', models.JSONField(default=dict)),
                ('selected_text', models.TextField(blank=True, default='')),
                ('note_content', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='gold', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='catalog.ouvrage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'ouvrage'], name='protection__user_id_7e1b8f_idx')],
            },
        ),
    ]
