# Generated by Django 5.2.13 on 2026-08-18 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ouvrage_price_digital_ouvrage_price_paper'),
        ('protection', '0002_annotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedCacheRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_identifier', models.CharField(db_index=True, max_length=255)),
                ('user_identifier', models.CharField(db_index=True, max_length=128)),
                ('file_path', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField()),
                ('config_version', models.IntegerField(default=1)),
                ('profil', models.CharField(default='standard', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='traceacces',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='protectionconfig',
            name='config_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='protectionconfig',
            name='lcp_drm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protectionconfig',
            name='loan_duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='protectionconfig',
            name='max_devices_per_user',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='protectionconfig',
            name='profil',
            field=models.CharField(choices=[('standard', 'Standard (Texte actif pour TTS & annotations)'), ('renforce', 'Renforcé (Pages images sans couche texte)')], default='standard', max_length=16),
        ),
        migrations.AddField(
            model_name='protectionconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='protectionconfig',
            name='watermark_opacity',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3),
        ),
        migrations.AddField(
            model_name='protectionconfig',
            name='watermark_position',
            field=models.CharField(choices=[('diagonal', 'Diagonale'), ('header', 'En-tête'), ('footer', 'Pied de page')], default='diagonal', max_length=32),
        ),
        migrations.AddField(
            model_name='traceacces',
            name='derived_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='traceacces',
            name='document_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='traceacces',
            name='partner_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='protectionconfig',
            name='invisible_watermark_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='protectionconfig',
            name='watermark_text_template',
            field=models.CharField(default='Licence accordée à {nom} ({email}) - IP: {ip}', max_length=255),
        ),
        migrations.AlterField(
            model_name='traceacces',
            name='access_type',
            field=models.CharField(choices=[('read_online', 'Lecture en ligne'), ('read_chunk', 'Lecture fragment Range 206'), ('text_request', 'Requête texte TTS'), ('audio_stream', 'Streaming audio')], db_index=True, default='read_chunk', max_length=32),
        ),
        migrations.AlterField(
            model_name='traceacces',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='traceacces',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='traceacces',
            name='ouvrage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traces_acces', to='catalog.ouvrage'),
        ),
        migrations.AlterField(
            model_name='traceacces',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces_acces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traceacces',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='traceacces',
            index=models.Index(fields=['user', 'ouvrage', '-timestamp'], name='protection__user_id_66abc3_idx'),
        ),
        migrations.AddIndex(
            model_name='traceacces',
            index=models.Index(fields=['ip_address', '-timestamp'], name='protection__ip_addr_9f1cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='traceacces',
            index=models.Index(fields=['country', '-timestamp'], name='protection__country_7428bb_idx'),
        ),
    ]
