# Generated by Django 5.2.13 on 2026-08-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protection', '0003_derivedcacheregistry_alter_traceacces_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDrmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_default', models.CharField(choices=[('standard', 'Standard (Texte actif pour TTS & annotations)'), ('renforce', 'Renforcé (Pages images sans couche texte)')], default='standard', max_length=16)),
                ('watermark_template', models.CharField(default='Licence accordée à {nom} ({email}) - IP: {ip}', help_text='Variables disponibles : {nom}, {email}, {ip}', max_length=500)),
                ('watermark_position', models.CharField(choices=[('diagonal', 'Diagonale'), ('header', 'En-tête'), ('footer', 'Pied de page')], default='diagonal', max_length=32)),
                ('watermark_opacity', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('invisible_watermark_enabled', models.BooleanField(default=True)),
                ('allow_print', models.BooleanField(default=False)),
                ('allow_copy', models.BooleanField(default=False)),
                ('max_devices', models.IntegerField(default=3)),
                ('session_duration_minutes', models.IntegerField(default=15)),
                ('config_version', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration DRM Globale',
                'verbose_name_plural': 'Configuration DRM Globale',
            },
        ),
    ]
