# Generated by Django 5.2.13 on 2026-08-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protection', '0004_global_drm_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaldrmconfig',
            name='watermark_laha_subtext',
            field=models.CharField(default='Licence accordée au Lecteur Authentifié • Reproduction interdite', help_text='Sous-texte légal du filigrane institutionnel LAHAThèque', max_length=500),
        ),
        migrations.AddField(
            model_name='globaldrmconfig',
            name='watermark_laha_template',
            field=models.CharField(default='LAHAThèque • Document Certifié & Protégé', help_text='Texte principal du filigrane institutionnel LAHAThèque. Variables : {titre}, {id}', max_length=500),
        ),
    ]
