# Generated by Django 5.2.7 on 2026-08-30 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_remove_bouquetoffering_books_count_and_more'),
        ('protection', '0005_add_laha_watermark_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceacces',
            name='bouquet_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces_acces', to='partners.universitybouquetsubscription'),
        ),
        migrations.AddField(
            model_name='traceacces',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces_acces', to='partners.institution'),
        ),
    ]
