# Generated by Django 5.2.7 on 2026-09-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protection', '0006_traceacces_bouquet_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceacces',
            name='access_type',
            field=models.CharField(choices=[('read_online', 'Lecture en ligne'), ('read_chunk', 'Lecture fragment Range 206'), ('text_request', 'Requête texte TTS'), ('audio_stream', 'Streaming audio'), ('download', 'Téléchargement')], db_index=True, default='read_chunk', max_length=32),
        ),
    ]
