# Generated by Django 5.2.13 on 2026-09-11 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_ouvragelanguageversion'),
        ('protection', '0007_alter_traceacces_access_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicInvestigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'Document PDF'), ('image', "Capture d'écran / Photo")], default='pdf', max_length=32)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(db_index=True, help_text='Empreinte SHA-256 du fichier suspect', max_length=64)),
                ('analysis_mode', models.CharField(choices=[('pdf_steganography', 'Stéganographie binaire PDF PyMuPDF'), ('local_ocr', "Prétraitement d'image et OCR local"), ('multimodal_vision', 'Vision multimodale haute précision'), ('inconclusive', 'Analyse sans résultat probant')], default='inconclusive', max_length=32)),
                ('certainty_score', models.IntegerField(default=0, help_text='Degré de certitude calculé entre 0 et 100%')),
                ('status', models.CharField(choices=[('identified', 'Fuite et lecteur formellement identifiés'), ('inconclusive', 'Indices partiels / Identification non concluante'), ('no_trace', 'Aucune empreinte ou filigrane détecté')], db_index=True, default='no_trace', max_length=32)),
                ('detected_payload', models.JSONField(blank=True, default=dict, help_text='Données brutes extraites (tatouage ou texte visuel)')),
                ('suspect_email', models.CharField(blank=True, default='', max_length=255)),
                ('suspect_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('order_reference', models.CharField(blank=True, default='', max_length=64)),
                ('actions_taken', models.JSONField(blank=True, default=list, help_text='Sanctions appliquées (account_suspended, sessions_revoked, report_exported)')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(help_text="Administrateur ayant diligenté l'investigation forensique", on_delete=django.db.models.deletion.CASCADE, related_name='forensic_investigations', to=settings.AUTH_USER_MODEL)),
                ('ouvrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forensic_investigations', to='catalog.ouvrage')),
                ('suspect_user', models.ForeignKey(blank=True, help_text="Lecteur formellement rattaché à l'empreinte", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forensic_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investigation Forensique',
                'verbose_name_plural': 'Investigations Forensiques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash'], name='protection__file_ha_63c01b_idx'), models.Index(fields=['status', '-created_at'], name='protection__status_5f2e5f_idx'), models.Index(fields=['suspect_user', '-created_at'], name='protection__suspect_84a362_idx')],
            },
        ),
    ]
