# Generated by Django 5.2.13 on 2026-09-11 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protection', '0008_forensicinvestigation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedReaderIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.CharField(blank=True, db_index=True, help_text='Identifiant du partenaire SaaS (ex: LAHALEX)', max_length=64)),
                ('reader_email', models.CharField(blank=True, db_index=True, help_text='Adresse email ou identifiant du lecteur tiers', max_length=255)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, help_text='Empreinte matérielle du terminal', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP dernièrement utilisée', null=True)),
                ('reason', models.TextField(blank=True, default='Fuite de document protégée identifiée par analyse forensique')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_readers_issued', to=settings.AUTH_USER_MODEL)),
                ('forensic_investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_identities', to='protection.forensicinvestigation')),
            ],
            options={
                'verbose_name': 'Lecteur Partenaire Bloqué',
                'verbose_name_plural': 'Lecteurs Partenaires Bloqués',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reader_email', 'is_active'], name='protection__reader__74ec16_idx'), models.Index(fields=['device_fingerprint', 'is_active'], name='protection__device__079823_idx'), models.Index(fields=['partner_id', 'is_active'], name='protection__partner_309aca_idx')],
            },
        ),
    ]
