# Generated by Django 5.2.13 on 2026-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_bank_name_user_iban_user_momo_number_user_swift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant / Client Lecteur'), ('teacher', 'Enseignant'), ('university', 'Université (Établissement Partenaire)'), ('publisher', 'Éditeur Tiers'), ('author', 'Auteur'), ('legal_reviewer', 'Relecteur Juridique / Juriste'), ('layout_artist', 'Maquettiste'), ('chief_layout', 'Chef Maquettiste'), ('manager', 'Gestionnaire Stock & Livraison'), ('partner_api', 'Partenaire API'), ('wholesaler', 'Grossiste'), ('admin', 'Administrateur'), ('super_admin', 'Super Admin')], default='student', max_length=30),
        ),
    ]
