# Generated by Django 5.2.7 on 2026-09-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedPartnerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('partner_id', models.UUIDField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration naturelle du jeton")),
            ],
            options={
                'verbose_name': 'Jeton Partenaire Révoqué',
                'verbose_name_plural': 'Jetons Partenaires Révoqués',
                'db_table': 'oauth2_revoked_partner_token',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
