# Generated by Django 5.2.13 on 2026-09-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_managers_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_remise_audio_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remise spécifique audio pour cet auteur en % (null = défaut plateforme)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_remise_numerique_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remise spécifique numérique pour cet auteur en % (null = défaut plateforme)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_remise_papier_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remise spécifique papier pour cet auteur en % (null = défaut plateforme)', max_digits=5, null=True),
        ),
    ]
