# Generated by Django 5.2 on 2026-09-10
from django.db import migrations

def mark_existing_users_verified(apps, schema_editor):
    """
    Marque tous les utilisateurs déjà existants en base de données comme vérifiés
    afin qu'aucun ancien compte ne soit bloqué par le nouveau système OTP d'inscription.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_verified=False).update(is_verified=True)

def reverse_code(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_custom_remise_audio_pct_and_more'),
    ]

    operations = [
        migrations.RunPython(mark_existing_users_verified, reverse_code=reverse_code),
    ]
