# Generated by Django 5.2.7 on 2026-09-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mark_existing_users_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
