# Generated by Django 5.2.7 on 2026-08-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('duration_seconds', models.IntegerField()),
                ('stream_id', models.CharField(max_length=255)),
                ('hls_manifest_url', models.URLField()),
                ('captions_vtt_url', models.URLField(blank=True, null=True)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='catalog.ouvrage')),
            ],
        ),
    ]
