# Generated by Django 5.2.7 on 2026-09-06 11:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
        ('catalog', '0017_ouvrage_has_audio_version_ouvrage_price_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioListeningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_listened_seconds', models.IntegerField(default=0)),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='audio.audiotrack')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='catalog.ouvrage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'audio_track', '-created_at'], name='audio_audio_user_id_9777a2_idx'), models.Index(fields=['ouvrage', 'session_date'], name='audio_audio_ouvrage_eaba60_idx')],
            },
        ),
    ]
