# Generated by Django 5.2.13 on 2026-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audiolisteningsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiotrack',
            options={'ordering': ['voice_gender', 'track_type', 'order_index', 'chapter_number']},
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='audio_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='audio_tracks/'),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='bitrate_kbps',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='track_type',
            field=models.CharField(choices=[('full', 'Livre complet'), ('chapter', 'Chapitre')], default='chapter', max_length=10),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='voice_gender',
            field=models.CharField(choices=[('male', 'Voix Homme'), ('female', 'Voix Femme')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='captions_vtt_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='chapter_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='hls_manifest_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='stream_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
