# Generated by Django 5.2.13 on 2026-09-08 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_alter_audiotrack_options_audiotrack_audio_file_and_more'),
        ('catalog', '0020_ouvragelanguageversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='language_version',
            field=models.ForeignKey(blank=True, help_text='Version linguistique spécifique à laquelle cette piste audio est rattachée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_tracks', to='catalog.ouvragelanguageversion'),
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='narration_language',
            field=models.CharField(blank=True, default='fr', help_text='Code ISO de la langue de narration (ex: fr, en)', max_length=10),
        ),
    ]
