# Generated by Django 5.2.7 on 2026-08-09 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('publishers_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code_dewey', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('biography', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='catalog.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='BJ', max_length=2)),
                ('format_type', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('audio', 'Audio')], max_length=20)),
                ('file', models.FileField(upload_to='books/')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('publication_date', models.DateField()),
                ('language', models.CharField(default='fr', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('table_of_contents', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('protection_type', models.CharField(default='lcp', max_length=30)),
                ('authors', models.ManyToManyField(blank=True, related_name='ouvrages', to='catalog.bookauthor')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrages', to='catalog.discipline')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrages', to='partners.institution')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ouvrages', to='publishers_portal.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='MetadataONIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onix_xml', models.TextField()),
                ('onix_version', models.CharField(default='3.0', max_length=10)),
                ('last_imported_at', models.DateTimeField(auto_now=True)),
                ('ouvrage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onix_metadata', to='catalog.ouvrage')),
            ],
        ),
    ]
