# Generated by Django 5.2.7 on 2026-08-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='price_digital',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='price_paper',
            field=models.DecimalField(decimal_places=2, default=7500.0, max_digits=10),
        ),
    ]
