# Generated by Django 5.2.13 on 2026-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ouvrage_price_digital_ouvrage_price_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
