# Generated by Django 5.2.7 on 2026-08-21 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ouvrage_cover_image'),
        ('publishers_portal', '0002_remove_validationworkflowstep_submission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='dewey_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='target_audience',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='format_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('audio', 'Audio'), ('papier', 'Livre Papier')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ouvrages', to='publishers_portal.publisher'),
        ),
    ]
