# Generated by Django 5.2.7 on 2026-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_quiz_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='is_paper_available',
            field=models.BooleanField(default=False, help_text='Décision éditoriale du Chef Maquettiste — distincte du prix papier renseigné.', verbose_name='Disponible en version papier'),
        ),
    ]
