# Generated by Django 5.2.7 on 2026-08-24 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_ouvrage_is_paper_available'),
        ('rights', '0003_preeditiondossier_auteur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='pre_edition_dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ouvrages', to='rights.preeditiondossier'),
        ),
    ]
