# Generated by Django 5.2.13 on 2026-08-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_ouvrage_pre_edition_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='classification_source',
            field=models.CharField(blank=True, default='ai_suggested', max_length=30),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='language_source',
            field=models.CharField(blank=True, default='ai_suggested', max_length=30),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='summary_source',
            field=models.CharField(blank=True, default='ai_suggested', max_length=30),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='dewey_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
