# Generated by Django 5.2.13 on 2026-08-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_ouvrage_classification_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Motif de rejet ou demande de correction émis par le Chef Maquettiste', verbose_name='Motif de correction ou de rejet'),
        ),
    ]
