# Generated by Django 5.2.7 on 2026-08-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_ouvrage_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
