# Generated by Django 5.2.13 on 2026-08-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_discipline_created_at_discipline_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='books/'),
        ),
    ]
