# Generated by Django 5.2.7 on 2026-08-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_ouvrage_cover_image_alter_ouvrage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
