# Generated by Django 5.2.13 on 2026-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_ouvrage_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
