# Generated by Django 5.2.13 on 2026-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_ouvrage_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='publisher_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Maison d'édition / Éditeur"),
        ),
    ]
