# Generated by Django 5.2.7 on 2026-09-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_ouvrage_publisher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='has_audio_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='price_audio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
