# Generated by Django 5.2.13 on 2026-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_ouvrage_has_audio_version_ouvrage_price_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='audio_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending_layout_validation', 'En attente validation maquette'), ('pending_legal_validation', 'En attente validation juridique'), ('published', 'Publié'), ('rejected', 'Rejeté')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='price_audio_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
