# Generated by Django 5.2.13 on 2026-09-08 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_ouvrage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuvrageLanguageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, max_length=10)),
                ('is_original', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('r2_key_pdf', models.CharField(blank=True, default='', max_length=512)),
                ('r2_key_epub', models.CharField(blank=True, default='', max_length=512)),
                ('r2_key_audio', models.CharField(blank=True, default='', max_length=512)),
                ('cover_url', models.URLField(blank=True, default='', max_length=1024)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('is_paper_available', models.BooleanField(default=False)),
                ('paper_stock', models.PositiveIntegerField(default=0)),
                ('translation_status', models.CharField(choices=[('ready', 'Prêt'), ('in_progress', 'En cours de traduction'), ('draft', 'Brouillon')], db_index=True, default='ready', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_versions', to='catalog.ouvrage')),
            ],
            options={
                'ordering': ['-is_original', 'language'],
                'indexes': [models.Index(fields=['ouvrage', 'language'], name='catalog_ouv_ouvrage_0a97df_idx'), models.Index(fields=['language', 'is_original'], name='catalog_ouv_languag_d45378_idx')],
                'constraints': [models.UniqueConstraint(fields=('ouvrage', 'language'), name='unique_ouvrage_language_version')],
            },
        ),
    ]
