# Generated by Django 5.2.7 on 2026-09-16 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_ouvragelanguageversion'),
        ('partners', '0007_alter_institution_royalty_rate'),
        ('publishers_portal', '0004_publisherbookdeposit_editorial_status_and_more'),
        ('rights', '0013_payoutrequest_beneficiary_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ouvrage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='ouvrage',
            index=models.Index(fields=['status'], name='catalog_ouv_status_1ad6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrage',
            index=models.Index(fields=['status', '-created_at'], name='catalog_ouv_status_0b0ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrage',
            index=models.Index(fields=['publisher', 'status'], name='catalog_ouv_publish_ffc45e_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrage',
            index=models.Index(fields=['discipline', 'status'], name='catalog_ouv_discipl_91d119_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrage',
            index=models.Index(fields=['isbn'], name='catalog_ouv_isbn_2a4ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='ouvrage',
            index=models.Index(fields=['slug'], name='catalog_ouv_slug_295c0a_idx'),
        ),
    ]
