# Generated by Django 5.2.13 on 2026-08-20 17:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_ouvrage_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('pages_read', models.IntegerField(default=0)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='catalog.ouvrage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de Lecture',
                'verbose_name_plural': 'Sessions de Lecture',
                'db_table': 'student_reading_session',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percent', models.IntegerField(default=0)),
                ('current_page', models.IntegerField(default=1)),
                ('total_pages', models.IntegerField(default=0)),
                ('last_read_chapter', models.CharField(blank=True, default='', max_length=255)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='catalog.ouvrage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression de Lecture',
                'verbose_name_plural': 'Progressions de Lecture',
                'db_table': 'student_reading_progress',
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'ouvrage')},
            },
        ),
    ]
