# Generated by Django 5.2.7 on 2026-08-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'Système'), ('message', 'Message'), ('booking_confirmed', 'Réservation Confirmée'), ('booking_reminder', 'Rappel Réservation'), ('community_reply', 'Réponse Communauté'), ('expert_question', 'Question Expert'), ('expert_reply', 'Réponse Expert'), ('assignment_created', 'Devoir Créé'), ('assignment_graded', 'Devoir Noté'), ('assignment_submitted', 'Devoir Soumis'), ('assignment_overdue', 'Devoir En Retard')], default='system', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='resource_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_on_bookings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_on_community',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_on_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notify_on_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
