# Generated by Django 5.2.13 on 2026-08-21 01:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_notification_action_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPlateformeGlobale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prix_defaut_numerique_xof', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), help_text='Prix par défaut pour un livre numérique (XOF)', max_digits=12)),
                ('prix_defaut_papier_xof', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Prix par défaut pour un livre papier (XOF)', max_digits=12)),
                ('prix_defaut_audio_xof', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), help_text='Prix par défaut pour un livre audio (XOF)', max_digits=12)),
                ('prix_pass_mensuel_xof', models.DecimalField(decimal_places=2, default=Decimal('4500.00'), help_text="Tarif de l'abonnement Pass Étudiant mensuel (XOF)", max_digits=12)),
                ('prix_pass_annuel_xof', models.DecimalField(decimal_places=2, default=Decimal('45000.00'), help_text="Tarif de l'abonnement Pass Étudiant annuel (XOF)", max_digits=12)),
                ('devise_defaut', models.CharField(default='XOF', max_length=8)),
                ('watermark_texte_defaut', models.CharField(default='LAHAThèque • Document Protégé', help_text='Texte filigrane imprimé dynamiquement sur les pages de la liseuse', max_length=255)),
                ('watermark_opacite_defaut', models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Opacité du filigrane (0.10 à 0.40)', max_digits=3)),
                ('restriction_impression_defaut', models.BooleanField(default=True, help_text="Bloquer l'impression sur la liseuse")),
                ('restriction_capture_defaut', models.BooleanField(default=True, help_text="Protection contre les captures d'écran")),
                ('duree_session_lecture_minutes', models.IntegerField(default=15, help_text="Durée de validité d'un token éphémère de lecture")),
                ('delai_relance_depots_jours', models.IntegerField(default=7, help_text="Nombre de jours d'inactivité avant relance d'un dépôt de maquette")),
                ('delai_relance_impayes_jours', models.IntegerField(default=7, help_text="Nombre de jours avant relance d'une commande impayée")),
                ('delai_relance_abonnements_jours', models.IntegerField(default=15, help_text="Jours avant expiration pour alerter l'étudiant/université")),
                ('moneroo_actif', models.BooleanField(default=True)),
                ('stripe_actif', models.BooleanField(default=True)),
                ('fastermessage_sms_actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Plateforme Globale',
                'db_table': 'reporting_platform_config',
            },
        ),
        migrations.CreateModel(
            name='RelanceAutomatiqueLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_relance', models.CharField(choices=[('depot_en_attente', 'Dépôt de Maquette en Attente'), ('facture_impayee', 'Facture / Commande Impayée'), ('abonnement_expiration', 'Expiration Abonnement / Bouquet')], db_index=True, max_length=40)),
                ('canal', models.CharField(choices=[('email', 'Courrier Électronique'), ('sms', 'SMS (FasterMessage)'), ('in_app', 'Notification In-App')], default='email', max_length=20)),
                ('destinataire_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('destinataire_telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('destinataire_nom', models.CharField(max_length=255)),
                ('objet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé avec succès'), ('echec', 'Échec de transmission'), ('ouvert', 'Consulté / Cliqué')], db_index=True, default='envoye', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text="ID du dépôt, de la commande ou de l'abonnement", max_length=128, null=True)),
                ('erreur_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'reporting_relance_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalAuditAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('ressource_type', models.CharField(db_index=True, max_length=64)),
                ('ressource_id', models.CharField(blank=True, max_length=128, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporting_admin_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
