# Generated by Django 5.2.7 on 2026-08-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_configurationplateformeglobale_relanceautomatiquelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'Système'), ('message', 'Message'), ('booking_confirmed', 'Réservation Confirmée'), ('booking_reminder', 'Rappel Réservation'), ('community_reply', 'Réponse Communauté'), ('expert_question', 'Question Expert'), ('expert_reply', 'Réponse Expert'), ('assignment_created', 'Devoir Créé'), ('assignment_graded', 'Devoir Noté'), ('assignment_submitted', 'Devoir Soumis'), ('assignment_overdue', 'Devoir En Retard'), ('payment_success', 'Paiement Confirmé'), ('payment_failed', 'Paiement Échoué'), ('order_shipped', 'Commande Expédiée'), ('order_delivered', 'Commande Livrée')], default='system', max_length=50),
        ),
    ]
