# Generated by Django 5.2.7 on 2026-08-26 01:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_add_delivery_order_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='remise_auteur_numerique_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Remise numérique accordée aux Auteurs (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='remise_auteur_papier_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Remise papier accordée aux Auteurs (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='remise_campus_numerique_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Remise numérique accordée aux Universités/Campus (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='remise_campus_papier_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Remise papier accordée aux Universités/Campus (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='remise_grossiste_numerique_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Remise numérique accordée aux Grossistes B2B (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='remise_grossiste_papier_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('32.00'), help_text='Remise papier accordée aux Grossistes B2B (%)', max_digits=5),
        ),
    ]
