# Generated by Django 5.2.13 on 2026-09-07 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='remise_auteur_audio_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Remise audio accordée aux Auteurs (%)', max_digits=5),
        ),
    ]
