# Generated by Django 5.2.13 on 2026-09-08 03:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_configurationplateformeglobale_remise_auteur_audio_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='default_author_royalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text="Taux standard des droits d'auteur (%)", max_digits=5),
        ),
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='default_platform_share_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Commission de la plateforme (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='default_publisher_royalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.00'), help_text='Taux standard des éditeurs tiers (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='configurationplateformeglobale',
            name='default_university_royalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Taux standard des universités partenaires (%)', max_digits=5),
        ),
    ]
