# Generated by Django 5.2.7 on 2026-09-11 14:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_configurationplateformeglobale_default_author_royalty_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationplateformeglobale',
            name='default_university_royalty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('15.00'), help_text='Taux standard des universités partenaires (%)', max_digits=5, null=True),
        ),
    ]
